[[pages]]
path = "tool_pages/main_page.py"
name = "é¦–é¡µ"
icon = "ğŸ "

[[pages]]
path = "tool_pages/car_position_calibration.py"
name = "ç©¿æ¢­è½¦ä½ç½®æ ¡å‡†"
icon = "âš™ï¸"

[[pages]]
path = "tool_pages/car_move.py"
name = "ç©¿æ¢­è½¦ç§»åŠ¨æ“ä½œ"
icon = "ğŸš—" 

[[pages]]
path = "tool_pages/task_outband.py"
name = "å‡ºåº“æ“ä½œ"
icon = "ğŸ“¤"

[[pages]]
path = "tool_pages/task_inband.py"
name = "å…¥åº“æ“ä½œ"
icon = "ğŸ“¥" 

[[pages]]
path = "tool_pages/good_move.py"
name = "è´§ç‰©ç§»åŠ¨æ“ä½œ"
icon = "ğŸ“¦" 

[[pages]]
path = "tool_pages/car_cross_layer.py"
name = "ç©¿æ¢­è½¦è·¨å±‚æ“ä½œ"
icon = "ğŸšš" 

[[pages]]
path = "test_bar.py"
name = "è¿›åº¦æ¡æµ‹è¯•"
icon = "ğŸ§­" 