[[pages]]
path = "tool_pages/main_page.py"
name = "é¦–é¡µ"
icon = "ğŸ "

[[pages]]
path = "tool_pages/car_position_calibration.py"
name = "ç©¿æ¢­è½¦ä½ç½®æ ¡å‡†"
icon = "âš™ï¸"

[[pages]]
path = "tool_pages/car_move.py"
name = "ç©¿æ¢­è½¦ç§»åŠ¨æ“ä½œ"
icon = "ğŸš—" 

[[pages]]
path = "tool_pages/good_move.py"
name = "è´§ç‰©ç§»åŠ¨æ“ä½œ"
icon = "ğŸ“¦" 

[[pages]]
path = "tool_pages/task_outband_by_step.py"
name = "å•æ­¥ - å‡ºåº“æ“ä½œ"
icon = "ğŸ“¤"

[[pages]]
path = "tool_pages/task_inband_by_step.py"
name = "å•æ­¥ - å…¥åº“æ“ä½œ"
icon = "ğŸ“¥" 

[[pages]]
path = "tool_pages/car_cross_layer_by_step.py"
name = "å•æ­¥ - ç©¿æ¢­è½¦è·¨å±‚æ“ä½œ"
icon = "ğŸšš" 

[[pages]]
path = "tool_pages/task_auto.py"
name = "beta - è‡ªåŠ¨åŒ–æ“ä½œ"
icon = "ğŸš¦" 

[[pages]]
path = "tool_pages/car_cross_layer.py"
name = "beta - ç©¿æ¢­è½¦è·¨å±‚æ“ä½œ"
icon = "ğŸšš" 

[[pages]]
path = "tool_pages/task_inband.py"
name = "beta - å…¥åº“æ“ä½œ"
icon = "ğŸ“¥" 

[[pages]]
path = "tool_pages/task_outband.py"
name = "beta - å‡ºåº“æ“ä½œ"
icon = "ğŸ“¤"